//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardBurner2.SmartCardHelperService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EInitSCardType", Namespace="http://schemas.datacontract.org/2004/07/DVS.Utilities.SecureLogin")]
    public enum EInitSCardType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoterCard = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdminCard = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyCard = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownCard = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoterFile", Namespace="http://schemas.datacontract.org/2004/07/DVS.Utilities.SecureLogin")]
    [System.SerializableAttribute()]
    public partial class VoterFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvsModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreationTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndexesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvisionalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProvisionalModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TabulatorNumberField;
        
        private byte[] VerificationCodeField;
        
        private string VoterSessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VotingEndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VotingSessionStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvsMode {
            get {
                return this.AvsModeField;
            }
            set {
                if ((object.ReferenceEquals(this.AvsModeField, value) != true)) {
                    this.AvsModeField = value;
                    this.RaisePropertyChanged("AvsMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreationTimeStamp {
            get {
                return this.CreationTimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.CreationTimeStampField, value) != true)) {
                    this.CreationTimeStampField = value;
                    this.RaisePropertyChanged("CreationTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Indexes {
            get {
                return this.IndexesField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexesField, value) != true)) {
                    this.IndexesField = value;
                    this.RaisePropertyChanged("Indexes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProvisionalCode {
            get {
                return this.ProvisionalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvisionalCodeField, value) != true)) {
                    this.ProvisionalCodeField = value;
                    this.RaisePropertyChanged("ProvisionalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProvisionalMode {
            get {
                return this.ProvisionalModeField;
            }
            set {
                if ((this.ProvisionalModeField.Equals(value) != true)) {
                    this.ProvisionalModeField = value;
                    this.RaisePropertyChanged("ProvisionalMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecordId {
            get {
                return this.RecordIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordIdField, value) != true)) {
                    this.RecordIdField = value;
                    this.RaisePropertyChanged("RecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TabulatorNumber {
            get {
                return this.TabulatorNumberField;
            }
            set {
                if ((this.TabulatorNumberField.Equals(value) != true)) {
                    this.TabulatorNumberField = value;
                    this.RaisePropertyChanged("TabulatorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] VerificationCode {
            get {
                return this.VerificationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VerificationCodeField, value) != true)) {
                    this.VerificationCodeField = value;
                    this.RaisePropertyChanged("VerificationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string VoterSessionId {
            get {
                return this.VoterSessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VoterSessionIdField, value) != true)) {
                    this.VoterSessionIdField = value;
                    this.RaisePropertyChanged("VoterSessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VotingEndTime {
            get {
                return this.VotingEndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.VotingEndTimeField, value) != true)) {
                    this.VotingEndTimeField = value;
                    this.RaisePropertyChanged("VotingEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VotingSessionStatus {
            get {
                return this.VotingSessionStatusField;
            }
            set {
                if ((this.VotingSessionStatusField.Equals(value) != true)) {
                    this.VotingSessionStatusField = value;
                    this.RaisePropertyChanged("VotingSessionStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EResultCode", Namespace="http://schemas.datacontract.org/2004/07/DVS.Utilities.SecureLogin")]
    public enum EResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoterSessionIdValidationError = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProvisionalCodeValidationError = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProvisionalModeValidationError = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AvsModeValidationError = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LanguageValidationError = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VotingSessionStatusValidationError = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorCodeValidationError = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreationTimeStampValidationError = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeValidationError = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RecordIdCodeValidationError = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IndexesCodeValidationError = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VotingEndTimeValidationError = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserTypeValidationError = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserIdValidationError = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExpirationTimeStampValidationError = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdminPinValidationError = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UrlValidationError = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RKeyValidationError = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RVectorValidationError = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HmacValidationError = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ElectionSignatureValidationError = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WrongPin = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LockedPin = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WrongCardType = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardNotPresented = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardNotEmpty = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorCleaning = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorInitializing = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorWriting = 100,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdminFile", Namespace="http://schemas.datacontract.org/2004/07/DVS.Utilities.SecureLogin")]
    [System.SerializableAttribute()]
    public partial class AdminFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AdminPinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreationTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ElectionSignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        private string ExpirationTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] HmacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RkeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RvectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AdminPin {
            get {
                return this.AdminPinField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminPinField, value) != true)) {
                    this.AdminPinField = value;
                    this.RaisePropertyChanged("AdminPin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreationTimeStamp {
            get {
                return this.CreationTimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.CreationTimeStampField, value) != true)) {
                    this.CreationTimeStampField = value;
                    this.RaisePropertyChanged("CreationTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ElectionSignature {
            get {
                return this.ElectionSignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.ElectionSignatureField, value) != true)) {
                    this.ElectionSignatureField = value;
                    this.RaisePropertyChanged("ElectionSignature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExpirationTimeStamp {
            get {
                return this.ExpirationTimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpirationTimeStampField, value) != true)) {
                    this.ExpirationTimeStampField = value;
                    this.RaisePropertyChanged("ExpirationTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Hmac {
            get {
                return this.HmacField;
            }
            set {
                if ((object.ReferenceEquals(this.HmacField, value) != true)) {
                    this.HmacField = value;
                    this.RaisePropertyChanged("Hmac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Rkey {
            get {
                return this.RkeyField;
            }
            set {
                if ((object.ReferenceEquals(this.RkeyField, value) != true)) {
                    this.RkeyField = value;
                    this.RaisePropertyChanged("Rkey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Rvector {
            get {
                return this.RvectorField;
            }
            set {
                if ((object.ReferenceEquals(this.RvectorField, value) != true)) {
                    this.RvectorField = value;
                    this.RaisePropertyChanged("Rvector");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://DVS.SmartCardHelperService", ConfigurationName="SmartCardHelperService.ISmartCardHelper")]
    public interface ISmartCardHelper {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/CardPresent", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/CardPresentResponse")]
        bool CardPresent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/CardPresent", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/CardPresentResponse")]
        System.Threading.Tasks.Task<bool> CardPresentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/CardReadersList", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/CardReadersListResponse")]
        string[] CardReadersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/CardReadersList", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/CardReadersListResponse")]
        System.Threading.Tasks.Task<string[]> CardReadersListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/ChangeSecurityPin", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/ChangeSecurityPinResponse")]
        CardBurner2.SmartCardHelperService.ChangeSecurityPinResponse ChangeSecurityPin(CardBurner2.SmartCardHelperService.ChangeSecurityPinRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/ChangeSecurityPin", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/ChangeSecurityPinResponse")]
        System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.ChangeSecurityPinResponse> ChangeSecurityPinAsync(CardBurner2.SmartCardHelperService.ChangeSecurityPinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/ChangeUserPin", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/ChangeUserPinResponse")]
        CardBurner2.SmartCardHelperService.ChangeUserPinResponse ChangeUserPin(CardBurner2.SmartCardHelperService.ChangeUserPinRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/ChangeUserPin", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/ChangeUserPinResponse")]
        System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.ChangeUserPinResponse> ChangeUserPinAsync(CardBurner2.SmartCardHelperService.ChangeUserPinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/CheckCardType", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/CheckCardTypeResponse")]
        CardBurner2.SmartCardHelperService.EInitSCardType CheckCardType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/CheckCardType", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/CheckCardTypeResponse")]
        System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.EInitSCardType> CheckCardTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/ReadVoterFile", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/ReadVoterFileResponse")]
        CardBurner2.SmartCardHelperService.ReadVoterFileResponse ReadVoterFile(CardBurner2.SmartCardHelperService.ReadVoterFileRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/ReadVoterFile", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/ReadVoterFileResponse")]
        System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.ReadVoterFileResponse> ReadVoterFileAsync(CardBurner2.SmartCardHelperService.ReadVoterFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/ClearSmartCard", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/ClearSmartCardResponse")]
        CardBurner2.SmartCardHelperService.EResultCode ClearSmartCard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/ClearSmartCard", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/ClearSmartCardResponse")]
        System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.EResultCode> ClearSmartCardAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/WriteVoterFile", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/WriteVoterFileResponse")]
        CardBurner2.SmartCardHelperService.EResultCode WriteVoterFile(string pin, CardBurner2.SmartCardHelperService.VoterFile voterFile, bool overWrite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/WriteVoterFile", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/WriteVoterFileResponse")]
        System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.EResultCode> WriteVoterFileAsync(string pin, CardBurner2.SmartCardHelperService.VoterFile voterFile, bool overWrite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/ReadAdminFile", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/ReadAdminFileResponse")]
        CardBurner2.SmartCardHelperService.ReadAdminFileResponse ReadAdminFile(CardBurner2.SmartCardHelperService.ReadAdminFileRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/ReadAdminFile", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/ReadAdminFileResponse")]
        System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.ReadAdminFileResponse> ReadAdminFileAsync(CardBurner2.SmartCardHelperService.ReadAdminFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/WriteAdminFile", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/WriteAdminFileResponse")]
        CardBurner2.SmartCardHelperService.EResultCode WriteAdminFile(string pin, string securityPin, CardBurner2.SmartCardHelperService.AdminFile adminFile, bool overWrite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/WriteAdminFile", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/WriteAdminFileResponse")]
        System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.EResultCode> WriteAdminFileAsync(string pin, string securityPin, CardBurner2.SmartCardHelperService.AdminFile adminFile, bool overWrite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/SelectCardReader", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/SelectCardReaderResponse")]
        bool SelectCardReader(string readerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/SelectCardReader", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/SelectCardReaderResponse")]
        System.Threading.Tasks.Task<bool> SelectCardReaderAsync(string readerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/VerifySecurityPin", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/VerifySecurityPinResponse")]
        CardBurner2.SmartCardHelperService.VerifySecurityPinResponse VerifySecurityPin(CardBurner2.SmartCardHelperService.VerifySecurityPinRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/VerifySecurityPin", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/VerifySecurityPinResponse")]
        System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.VerifySecurityPinResponse> VerifySecurityPinAsync(CardBurner2.SmartCardHelperService.VerifySecurityPinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/VerifyUserPin", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/VerifyUserPinResponse")]
        CardBurner2.SmartCardHelperService.VerifyUserPinResponse VerifyUserPin(CardBurner2.SmartCardHelperService.VerifyUserPinRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://DVS.SmartCardHelperService/ISmartCardHelper/VerifyUserPin", ReplyAction="http://DVS.SmartCardHelperService/ISmartCardHelper/VerifyUserPinResponse")]
        System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.VerifyUserPinResponse> VerifyUserPinAsync(CardBurner2.SmartCardHelperService.VerifyUserPinRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeSecurityPin", WrapperNamespace="http://DVS.SmartCardHelperService", IsWrapped=true)]
    public partial class ChangeSecurityPinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=0)]
        public string currentSecurityPin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=1)]
        public string newSecurityPin;
        
        public ChangeSecurityPinRequest() {
        }
        
        public ChangeSecurityPinRequest(string currentSecurityPin, string newSecurityPin) {
            this.currentSecurityPin = currentSecurityPin;
            this.newSecurityPin = newSecurityPin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeSecurityPinResponse", WrapperNamespace="http://DVS.SmartCardHelperService", IsWrapped=true)]
    public partial class ChangeSecurityPinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=0)]
        public bool ChangeSecurityPinResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=1)]
        public int retries;
        
        public ChangeSecurityPinResponse() {
        }
        
        public ChangeSecurityPinResponse(bool ChangeSecurityPinResult, int retries) {
            this.ChangeSecurityPinResult = ChangeSecurityPinResult;
            this.retries = retries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeUserPin", WrapperNamespace="http://DVS.SmartCardHelperService", IsWrapped=true)]
    public partial class ChangeUserPinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=0)]
        public string securityPin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=1)]
        public string newUserPin;
        
        public ChangeUserPinRequest() {
        }
        
        public ChangeUserPinRequest(string securityPin, string newUserPin) {
            this.securityPin = securityPin;
            this.newUserPin = newUserPin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeUserPinResponse", WrapperNamespace="http://DVS.SmartCardHelperService", IsWrapped=true)]
    public partial class ChangeUserPinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=0)]
        public bool ChangeUserPinResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=1)]
        public int retries;
        
        public ChangeUserPinResponse() {
        }
        
        public ChangeUserPinResponse(bool ChangeUserPinResult, int retries) {
            this.ChangeUserPinResult = ChangeUserPinResult;
            this.retries = retries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadVoterFile", WrapperNamespace="http://DVS.SmartCardHelperService", IsWrapped=true)]
    public partial class ReadVoterFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=0)]
        public string pin;
        
        public ReadVoterFileRequest() {
        }
        
        public ReadVoterFileRequest(string pin) {
            this.pin = pin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadVoterFileResponse", WrapperNamespace="http://DVS.SmartCardHelperService", IsWrapped=true)]
    public partial class ReadVoterFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=0)]
        public CardBurner2.SmartCardHelperService.VoterFile ReadVoterFileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=1)]
        public int retries;
        
        public ReadVoterFileResponse() {
        }
        
        public ReadVoterFileResponse(CardBurner2.SmartCardHelperService.VoterFile ReadVoterFileResult, int retries) {
            this.ReadVoterFileResult = ReadVoterFileResult;
            this.retries = retries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAdminFile", WrapperNamespace="http://DVS.SmartCardHelperService", IsWrapped=true)]
    public partial class ReadAdminFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=0)]
        public string pin;
        
        public ReadAdminFileRequest() {
        }
        
        public ReadAdminFileRequest(string pin) {
            this.pin = pin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadAdminFileResponse", WrapperNamespace="http://DVS.SmartCardHelperService", IsWrapped=true)]
    public partial class ReadAdminFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=0)]
        public CardBurner2.SmartCardHelperService.AdminFile ReadAdminFileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=1)]
        public int retries;
        
        public ReadAdminFileResponse() {
        }
        
        public ReadAdminFileResponse(CardBurner2.SmartCardHelperService.AdminFile ReadAdminFileResult, int retries) {
            this.ReadAdminFileResult = ReadAdminFileResult;
            this.retries = retries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifySecurityPin", WrapperNamespace="http://DVS.SmartCardHelperService", IsWrapped=true)]
    public partial class VerifySecurityPinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=0)]
        public string securityPin;
        
        public VerifySecurityPinRequest() {
        }
        
        public VerifySecurityPinRequest(string securityPin) {
            this.securityPin = securityPin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifySecurityPinResponse", WrapperNamespace="http://DVS.SmartCardHelperService", IsWrapped=true)]
    public partial class VerifySecurityPinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=0)]
        public bool VerifySecurityPinResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=1)]
        public int retries;
        
        public VerifySecurityPinResponse() {
        }
        
        public VerifySecurityPinResponse(bool VerifySecurityPinResult, int retries) {
            this.VerifySecurityPinResult = VerifySecurityPinResult;
            this.retries = retries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyUserPin", WrapperNamespace="http://DVS.SmartCardHelperService", IsWrapped=true)]
    public partial class VerifyUserPinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=0)]
        public string userPin;
        
        public VerifyUserPinRequest() {
        }
        
        public VerifyUserPinRequest(string userPin) {
            this.userPin = userPin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyUserPinResponse", WrapperNamespace="http://DVS.SmartCardHelperService", IsWrapped=true)]
    public partial class VerifyUserPinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=0)]
        public bool VerifyUserPinResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://DVS.SmartCardHelperService", Order=1)]
        public int retries;
        
        public VerifyUserPinResponse() {
        }
        
        public VerifyUserPinResponse(bool VerifyUserPinResult, int retries) {
            this.VerifyUserPinResult = VerifyUserPinResult;
            this.retries = retries;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmartCardHelperChannel : CardBurner2.SmartCardHelperService.ISmartCardHelper, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmartCardHelperClient : System.ServiceModel.ClientBase<CardBurner2.SmartCardHelperService.ISmartCardHelper>, CardBurner2.SmartCardHelperService.ISmartCardHelper {
        
        public SmartCardHelperClient() {
        }
        
        public SmartCardHelperClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmartCardHelperClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartCardHelperClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartCardHelperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CardPresent() {
            return base.Channel.CardPresent();
        }
        
        public System.Threading.Tasks.Task<bool> CardPresentAsync() {
            return base.Channel.CardPresentAsync();
        }
        
        public string[] CardReadersList() {
            return base.Channel.CardReadersList();
        }
        
        public System.Threading.Tasks.Task<string[]> CardReadersListAsync() {
            return base.Channel.CardReadersListAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CardBurner2.SmartCardHelperService.ChangeSecurityPinResponse CardBurner2.SmartCardHelperService.ISmartCardHelper.ChangeSecurityPin(CardBurner2.SmartCardHelperService.ChangeSecurityPinRequest request) {
            return base.Channel.ChangeSecurityPin(request);
        }
        
        public bool ChangeSecurityPin(string currentSecurityPin, string newSecurityPin, out int retries) {
            CardBurner2.SmartCardHelperService.ChangeSecurityPinRequest inValue = new CardBurner2.SmartCardHelperService.ChangeSecurityPinRequest();
            inValue.currentSecurityPin = currentSecurityPin;
            inValue.newSecurityPin = newSecurityPin;
            CardBurner2.SmartCardHelperService.ChangeSecurityPinResponse retVal = ((CardBurner2.SmartCardHelperService.ISmartCardHelper)(this)).ChangeSecurityPin(inValue);
            retries = retVal.retries;
            return retVal.ChangeSecurityPinResult;
        }
        
        public System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.ChangeSecurityPinResponse> ChangeSecurityPinAsync(CardBurner2.SmartCardHelperService.ChangeSecurityPinRequest request) {
            return base.Channel.ChangeSecurityPinAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CardBurner2.SmartCardHelperService.ChangeUserPinResponse CardBurner2.SmartCardHelperService.ISmartCardHelper.ChangeUserPin(CardBurner2.SmartCardHelperService.ChangeUserPinRequest request) {
            return base.Channel.ChangeUserPin(request);
        }
        
        public bool ChangeUserPin(string securityPin, string newUserPin, out int retries) {
            CardBurner2.SmartCardHelperService.ChangeUserPinRequest inValue = new CardBurner2.SmartCardHelperService.ChangeUserPinRequest();
            inValue.securityPin = securityPin;
            inValue.newUserPin = newUserPin;
            CardBurner2.SmartCardHelperService.ChangeUserPinResponse retVal = ((CardBurner2.SmartCardHelperService.ISmartCardHelper)(this)).ChangeUserPin(inValue);
            retries = retVal.retries;
            return retVal.ChangeUserPinResult;
        }
        
        public System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.ChangeUserPinResponse> ChangeUserPinAsync(CardBurner2.SmartCardHelperService.ChangeUserPinRequest request) {
            return base.Channel.ChangeUserPinAsync(request);
        }
        
        public CardBurner2.SmartCardHelperService.EInitSCardType CheckCardType() {
            return base.Channel.CheckCardType();
        }
        
        public System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.EInitSCardType> CheckCardTypeAsync() {
            return base.Channel.CheckCardTypeAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CardBurner2.SmartCardHelperService.ReadVoterFileResponse CardBurner2.SmartCardHelperService.ISmartCardHelper.ReadVoterFile(CardBurner2.SmartCardHelperService.ReadVoterFileRequest request) {
            return base.Channel.ReadVoterFile(request);
        }
        
        public CardBurner2.SmartCardHelperService.VoterFile ReadVoterFile(string pin, out int retries) {
            CardBurner2.SmartCardHelperService.ReadVoterFileRequest inValue = new CardBurner2.SmartCardHelperService.ReadVoterFileRequest();
            inValue.pin = pin;
            CardBurner2.SmartCardHelperService.ReadVoterFileResponse retVal = ((CardBurner2.SmartCardHelperService.ISmartCardHelper)(this)).ReadVoterFile(inValue);
            retries = retVal.retries;
            return retVal.ReadVoterFileResult;
        }
        
        public System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.ReadVoterFileResponse> ReadVoterFileAsync(CardBurner2.SmartCardHelperService.ReadVoterFileRequest request) {
            return base.Channel.ReadVoterFileAsync(request);
        }
        
        public CardBurner2.SmartCardHelperService.EResultCode ClearSmartCard() {
            return base.Channel.ClearSmartCard();
        }
        
        public System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.EResultCode> ClearSmartCardAsync() {
            return base.Channel.ClearSmartCardAsync();
        }
        
        public CardBurner2.SmartCardHelperService.EResultCode WriteVoterFile(string pin, CardBurner2.SmartCardHelperService.VoterFile voterFile, bool overWrite) {
            return base.Channel.WriteVoterFile(pin, voterFile, overWrite);
        }
        
        public System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.EResultCode> WriteVoterFileAsync(string pin, CardBurner2.SmartCardHelperService.VoterFile voterFile, bool overWrite) {
            return base.Channel.WriteVoterFileAsync(pin, voterFile, overWrite);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CardBurner2.SmartCardHelperService.ReadAdminFileResponse CardBurner2.SmartCardHelperService.ISmartCardHelper.ReadAdminFile(CardBurner2.SmartCardHelperService.ReadAdminFileRequest request) {
            return base.Channel.ReadAdminFile(request);
        }
        
        public CardBurner2.SmartCardHelperService.AdminFile ReadAdminFile(string pin, out int retries) {
            CardBurner2.SmartCardHelperService.ReadAdminFileRequest inValue = new CardBurner2.SmartCardHelperService.ReadAdminFileRequest();
            inValue.pin = pin;
            CardBurner2.SmartCardHelperService.ReadAdminFileResponse retVal = ((CardBurner2.SmartCardHelperService.ISmartCardHelper)(this)).ReadAdminFile(inValue);
            retries = retVal.retries;
            return retVal.ReadAdminFileResult;
        }
        
        public System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.ReadAdminFileResponse> ReadAdminFileAsync(CardBurner2.SmartCardHelperService.ReadAdminFileRequest request) {
            return base.Channel.ReadAdminFileAsync(request);
        }
        
        public CardBurner2.SmartCardHelperService.EResultCode WriteAdminFile(string pin, string securityPin, CardBurner2.SmartCardHelperService.AdminFile adminFile, bool overWrite) {
            return base.Channel.WriteAdminFile(pin, securityPin, adminFile, overWrite);
        }
        
        public System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.EResultCode> WriteAdminFileAsync(string pin, string securityPin, CardBurner2.SmartCardHelperService.AdminFile adminFile, bool overWrite) {
            return base.Channel.WriteAdminFileAsync(pin, securityPin, adminFile, overWrite);
        }
        
        public bool SelectCardReader(string readerName) {
            return base.Channel.SelectCardReader(readerName);
        }
        
        public System.Threading.Tasks.Task<bool> SelectCardReaderAsync(string readerName) {
            return base.Channel.SelectCardReaderAsync(readerName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CardBurner2.SmartCardHelperService.VerifySecurityPinResponse CardBurner2.SmartCardHelperService.ISmartCardHelper.VerifySecurityPin(CardBurner2.SmartCardHelperService.VerifySecurityPinRequest request) {
            return base.Channel.VerifySecurityPin(request);
        }
        
        public bool VerifySecurityPin(string securityPin, out int retries) {
            CardBurner2.SmartCardHelperService.VerifySecurityPinRequest inValue = new CardBurner2.SmartCardHelperService.VerifySecurityPinRequest();
            inValue.securityPin = securityPin;
            CardBurner2.SmartCardHelperService.VerifySecurityPinResponse retVal = ((CardBurner2.SmartCardHelperService.ISmartCardHelper)(this)).VerifySecurityPin(inValue);
            retries = retVal.retries;
            return retVal.VerifySecurityPinResult;
        }
        
        public System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.VerifySecurityPinResponse> VerifySecurityPinAsync(CardBurner2.SmartCardHelperService.VerifySecurityPinRequest request) {
            return base.Channel.VerifySecurityPinAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CardBurner2.SmartCardHelperService.VerifyUserPinResponse CardBurner2.SmartCardHelperService.ISmartCardHelper.VerifyUserPin(CardBurner2.SmartCardHelperService.VerifyUserPinRequest request) {
            return base.Channel.VerifyUserPin(request);
        }
        
        public bool VerifyUserPin(string userPin, out int retries) {
            CardBurner2.SmartCardHelperService.VerifyUserPinRequest inValue = new CardBurner2.SmartCardHelperService.VerifyUserPinRequest();
            inValue.userPin = userPin;
            CardBurner2.SmartCardHelperService.VerifyUserPinResponse retVal = ((CardBurner2.SmartCardHelperService.ISmartCardHelper)(this)).VerifyUserPin(inValue);
            retries = retVal.retries;
            return retVal.VerifyUserPinResult;
        }
        
        public System.Threading.Tasks.Task<CardBurner2.SmartCardHelperService.VerifyUserPinResponse> VerifyUserPinAsync(CardBurner2.SmartCardHelperService.VerifyUserPinRequest request) {
            return base.Channel.VerifyUserPinAsync(request);
        }
    }
}
